// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Supported runtime control actions.
// Ref: #/components/schemas/ActionName
type ActionName string

const (
	ActionNameGc              ActionName = "gc"
	ActionNameFreeOsMemory    ActionName = "free-os-memory"
	ActionNameStorageMaintain ActionName = "storage-maintain"
)

// AllValues returns all ActionName values.
func (ActionName) AllValues() []ActionName {
	return []ActionName{
		ActionNameGc,
		ActionNameFreeOsMemory,
		ActionNameStorageMaintain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ActionName) MarshalText() ([]byte, error) {
	switch s {
	case ActionNameGc:
		return []byte(s), nil
	case ActionNameFreeOsMemory:
		return []byte(s), nil
	case ActionNameStorageMaintain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ActionName) UnmarshalText(data []byte) error {
	switch ActionName(data) {
	case ActionNameGc:
		*s = ActionNameGc
		return nil
	case ActionNameFreeOsMemory:
		*s = ActionNameFreeOsMemory
		return nil
	case ActionNameStorageMaintain:
		*s = ActionNameStorageMaintain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ActionResult
type ActionResult struct {
	Action ActionName `json:"action"`
	Ok     bool       `json:"ok"`
	// Human-readable outcome.
	Message string `json:"message"`
	// Heap bytes released, for memory-reclaiming actions.
	FreedBytes OptInt64 `json:"freed_bytes"`
}

// GetAction returns the value of Action.
func (s *ActionResult) GetAction() ActionName {
	return s.Action
}

// GetOk returns the value of Ok.
func (s *ActionResult) GetOk() bool {
	return s.Ok
}

// GetMessage returns the value of Message.
func (s *ActionResult) GetMessage() string {
	return s.Message
}

// GetFreedBytes returns the value of FreedBytes.
func (s *ActionResult) GetFreedBytes() OptInt64 {
	return s.FreedBytes
}

// SetAction sets the value of Action.
func (s *ActionResult) SetAction(val ActionName) {
	s.Action = val
}

// SetOk sets the value of Ok.
func (s *ActionResult) SetOk(val bool) {
	s.Ok = val
}

// SetMessage sets the value of Message.
func (s *ActionResult) SetMessage(val string) {
	s.Message = val
}

// SetFreedBytes sets the value of FreedBytes.
func (s *ActionResult) SetFreedBytes(val OptInt64) {
	s.FreedBytes = val
}

// Ingestion admission counters for a tenant.
// Ref: #/components/schemas/AdmissionStats
type AdmissionStats struct {
	Accepted int64 `json:"accepted"`
	// Rejected as out-of-order.
	RejectedOoo int64 `json:"rejected_ooo"`
	// Rejected by rate limit.
	RejectedRate int64 `json:"rejected_rate"`
	// Rejected by cardinality limit.
	RejectedCardinality int64 `json:"rejected_cardinality"`
	// Rejected due to in-flight admission pressure.
	RejectedInFlight int64 `json:"rejected_in_flight"`
	SampledDropped   int64 `json:"sampled_dropped"`
	Overflowed       int64 `json:"overflowed"`
}

// GetAccepted returns the value of Accepted.
func (s *AdmissionStats) GetAccepted() int64 {
	return s.Accepted
}

// GetRejectedOoo returns the value of RejectedOoo.
func (s *AdmissionStats) GetRejectedOoo() int64 {
	return s.RejectedOoo
}

// GetRejectedRate returns the value of RejectedRate.
func (s *AdmissionStats) GetRejectedRate() int64 {
	return s.RejectedRate
}

// GetRejectedCardinality returns the value of RejectedCardinality.
func (s *AdmissionStats) GetRejectedCardinality() int64 {
	return s.RejectedCardinality
}

// GetRejectedInFlight returns the value of RejectedInFlight.
func (s *AdmissionStats) GetRejectedInFlight() int64 {
	return s.RejectedInFlight
}

// GetSampledDropped returns the value of SampledDropped.
func (s *AdmissionStats) GetSampledDropped() int64 {
	return s.SampledDropped
}

// GetOverflowed returns the value of Overflowed.
func (s *AdmissionStats) GetOverflowed() int64 {
	return s.Overflowed
}

// SetAccepted sets the value of Accepted.
func (s *AdmissionStats) SetAccepted(val int64) {
	s.Accepted = val
}

// SetRejectedOoo sets the value of RejectedOoo.
func (s *AdmissionStats) SetRejectedOoo(val int64) {
	s.RejectedOoo = val
}

// SetRejectedRate sets the value of RejectedRate.
func (s *AdmissionStats) SetRejectedRate(val int64) {
	s.RejectedRate = val
}

// SetRejectedCardinality sets the value of RejectedCardinality.
func (s *AdmissionStats) SetRejectedCardinality(val int64) {
	s.RejectedCardinality = val
}

// SetRejectedInFlight sets the value of RejectedInFlight.
func (s *AdmissionStats) SetRejectedInFlight(val int64) {
	s.RejectedInFlight = val
}

// SetSampledDropped sets the value of SampledDropped.
func (s *AdmissionStats) SetSampledDropped(val int64) {
	s.SampledDropped = val
}

// SetOverflowed sets the value of Overflowed.
func (s *AdmissionStats) SetOverflowed(val int64) {
	s.Overflowed = val
}

// Ref: #/components/schemas/CacheStats
type CacheStats struct {
	DecodeCache DecodeCacheStats `json:"decode_cache"`
}

// GetDecodeCache returns the value of DecodeCache.
func (s *CacheStats) GetDecodeCache() DecodeCacheStats {
	return s.DecodeCache
}

// SetDecodeCache sets the value of DecodeCache.
func (s *CacheStats) SetDecodeCache(val DecodeCacheStats) {
	s.DecodeCache = val
}

// Deprecated ClickHouse storage statistics.
// Ref: #/components/schemas/ClickHouseStats
type ClickHouseStats struct {
	Tables []TableStats `json:"tables"`
}

// GetTables returns the value of Tables.
func (s *ClickHouseStats) GetTables() []TableStats {
	return s.Tables
}

// SetTables sets the value of Tables.
func (s *ClickHouseStats) SetTables(val []TableStats) {
	s.Tables = val
}

// Ref: #/components/schemas/ClusterMember
type ClusterMember struct {
	ID   string    `json:"id"`
	Zone OptString `json:"zone"`
	Addr OptString `json:"addr"`
}

// GetID returns the value of ID.
func (s *ClusterMember) GetID() string {
	return s.ID
}

// GetZone returns the value of Zone.
func (s *ClusterMember) GetZone() OptString {
	return s.Zone
}

// GetAddr returns the value of Addr.
func (s *ClusterMember) GetAddr() OptString {
	return s.Addr
}

// SetID sets the value of ID.
func (s *ClusterMember) SetID(val string) {
	s.ID = val
}

// SetZone sets the value of Zone.
func (s *ClusterMember) SetZone(val OptString) {
	s.Zone = val
}

// SetAddr sets the value of Addr.
func (s *ClusterMember) SetAddr(val OptString) {
	s.Addr = val
}

// Cluster membership, present only in cluster mode.
// Ref: #/components/schemas/ClusterStats
type ClusterStats struct {
	// This node's ring id.
	Self    string          `json:"self"`
	Members []ClusterMember `json:"members"`
	// Shard keys owned by this node.
	Owned    []string         `json:"owned"`
	PartSync OptPartSyncStats `json:"part_sync"`
	Ec       OptECStats       `json:"ec"`
}

// GetSelf returns the value of Self.
func (s *ClusterStats) GetSelf() string {
	return s.Self
}

// GetMembers returns the value of Members.
func (s *ClusterStats) GetMembers() []ClusterMember {
	return s.Members
}

// GetOwned returns the value of Owned.
func (s *ClusterStats) GetOwned() []string {
	return s.Owned
}

// GetPartSync returns the value of PartSync.
func (s *ClusterStats) GetPartSync() OptPartSyncStats {
	return s.PartSync
}

// GetEc returns the value of Ec.
func (s *ClusterStats) GetEc() OptECStats {
	return s.Ec
}

// SetSelf sets the value of Self.
func (s *ClusterStats) SetSelf(val string) {
	s.Self = val
}

// SetMembers sets the value of Members.
func (s *ClusterStats) SetMembers(val []ClusterMember) {
	s.Members = val
}

// SetOwned sets the value of Owned.
func (s *ClusterStats) SetOwned(val []string) {
	s.Owned = val
}

// SetPartSync sets the value of PartSync.
func (s *ClusterStats) SetPartSync(val OptPartSyncStats) {
	s.PartSync = val
}

// SetEc sets the value of Ec.
func (s *ClusterStats) SetEc(val OptECStats) {
	s.Ec = val
}

// Ref: #/components/schemas/ComponentHealth
type ComponentHealth struct {
	// Component/service name.
	Name   string       `json:"name"`
	Status HealthStatus `json:"status"`
	// Listen address, when the component is an HTTP server.
	Addr OptString `json:"addr"`
	// Last error, when unhealthy.
	Error OptString `json:"error"`
}

// GetName returns the value of Name.
func (s *ComponentHealth) GetName() string {
	return s.Name
}

// GetStatus returns the value of Status.
func (s *ComponentHealth) GetStatus() HealthStatus {
	return s.Status
}

// GetAddr returns the value of Addr.
func (s *ComponentHealth) GetAddr() OptString {
	return s.Addr
}

// GetError returns the value of Error.
func (s *ComponentHealth) GetError() OptString {
	return s.Error
}

// SetName sets the value of Name.
func (s *ComponentHealth) SetName(val string) {
	s.Name = val
}

// SetStatus sets the value of Status.
func (s *ComponentHealth) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetAddr sets the value of Addr.
func (s *ComponentHealth) SetAddr(val OptString) {
	s.Addr = val
}

// SetError sets the value of Error.
func (s *ComponentHealth) SetError(val OptString) {
	s.Error = val
}

// Decoded-column cache, summed across metric engines.
// Ref: #/components/schemas/DecodeCacheStats
type DecodeCacheStats struct {
	Hits   int64 `json:"hits"`
	Misses int64 `json:"misses"`
	Bytes  int64 `json:"bytes"`
	// Cached blocks.
	Items int64 `json:"items"`
}

// GetHits returns the value of Hits.
func (s *DecodeCacheStats) GetHits() int64 {
	return s.Hits
}

// GetMisses returns the value of Misses.
func (s *DecodeCacheStats) GetMisses() int64 {
	return s.Misses
}

// GetBytes returns the value of Bytes.
func (s *DecodeCacheStats) GetBytes() int64 {
	return s.Bytes
}

// GetItems returns the value of Items.
func (s *DecodeCacheStats) GetItems() int64 {
	return s.Items
}

// SetHits sets the value of Hits.
func (s *DecodeCacheStats) SetHits(val int64) {
	s.Hits = val
}

// SetMisses sets the value of Misses.
func (s *DecodeCacheStats) SetMisses(val int64) {
	s.Misses = val
}

// SetBytes sets the value of Bytes.
func (s *DecodeCacheStats) SetBytes(val int64) {
	s.Bytes = val
}

// SetItems sets the value of Items.
func (s *DecodeCacheStats) SetItems(val int64) {
	s.Items = val
}

// Cumulative erasure-coding activity of this node, present only when the cluster runs with a private
// (per-node) backend. All zeros when no tenant has an EC policy. A high reconstruct rate on cold reads
// is expected; growing errors are not.
// Ref: #/components/schemas/ECStats
type ECStats struct {
	// Cold parts erasure-coded by this node as their compaction owner.
	Converted int64 `json:"converted"`
	// Failed conversion attempts (retried on a later maintenance tick).
	ConvertErrors int64 `json:"convert_errors"`
	// Shard slots rebuilt from surviving shards.
	RepairedSlots int64 `json:"repaired_slots"`
	// Failed repair attempts.
	RepairErrors int64 `json:"repair_errors"`
	// Parts whose staged foreign shards were pruned after distribution.
	PrunedStagedParts int64 `json:"pruned_staged_parts"`
	// Read-path object reconstructions (no local full copy).
	Reconstructs int64 `json:"reconstructs"`
	// Reconstructions that failed and surfaced to the query.
	ReconstructErrors int64 `json:"reconstruct_errors"`
}

// GetConverted returns the value of Converted.
func (s *ECStats) GetConverted() int64 {
	return s.Converted
}

// GetConvertErrors returns the value of ConvertErrors.
func (s *ECStats) GetConvertErrors() int64 {
	return s.ConvertErrors
}

// GetRepairedSlots returns the value of RepairedSlots.
func (s *ECStats) GetRepairedSlots() int64 {
	return s.RepairedSlots
}

// GetRepairErrors returns the value of RepairErrors.
func (s *ECStats) GetRepairErrors() int64 {
	return s.RepairErrors
}

// GetPrunedStagedParts returns the value of PrunedStagedParts.
func (s *ECStats) GetPrunedStagedParts() int64 {
	return s.PrunedStagedParts
}

// GetReconstructs returns the value of Reconstructs.
func (s *ECStats) GetReconstructs() int64 {
	return s.Reconstructs
}

// GetReconstructErrors returns the value of ReconstructErrors.
func (s *ECStats) GetReconstructErrors() int64 {
	return s.ReconstructErrors
}

// SetConverted sets the value of Converted.
func (s *ECStats) SetConverted(val int64) {
	s.Converted = val
}

// SetConvertErrors sets the value of ConvertErrors.
func (s *ECStats) SetConvertErrors(val int64) {
	s.ConvertErrors = val
}

// SetRepairedSlots sets the value of RepairedSlots.
func (s *ECStats) SetRepairedSlots(val int64) {
	s.RepairedSlots = val
}

// SetRepairErrors sets the value of RepairErrors.
func (s *ECStats) SetRepairErrors(val int64) {
	s.RepairErrors = val
}

// SetPrunedStagedParts sets the value of PrunedStagedParts.
func (s *ECStats) SetPrunedStagedParts(val int64) {
	s.PrunedStagedParts = val
}

// SetReconstructs sets the value of Reconstructs.
func (s *ECStats) SetReconstructs(val int64) {
	s.Reconstructs = val
}

// SetReconstructErrors sets the value of ReconstructErrors.
func (s *ECStats) SetReconstructErrors(val int64) {
	s.ReconstructErrors = val
}

// Embedded storage capacity/efficiency breakdown.
// Ref: #/components/schemas/EfficiencyStats
type EfficiencyStats struct {
	// Whether the embedded oteldb/storage engine is active.
	StorageEnabled bool               `json:"storage_enabled"`
	Tenants        []TenantEfficiency `json:"tenants"`
}

// GetStorageEnabled returns the value of StorageEnabled.
func (s *EfficiencyStats) GetStorageEnabled() bool {
	return s.StorageEnabled
}

// GetTenants returns the value of Tenants.
func (s *EfficiencyStats) GetTenants() []TenantEfficiency {
	return s.Tenants
}

// SetStorageEnabled sets the value of StorageEnabled.
func (s *EfficiencyStats) SetStorageEnabled(val bool) {
	s.StorageEnabled = val
}

// SetTenants sets the value of Tenants.
func (s *EfficiencyStats) SetTenants(val []TenantEfficiency) {
	s.Tenants = val
}

// Per-signal engine statistics for a tenant.
// Ref: #/components/schemas/EngineSignalStats
type EngineSignalStats struct {
	Signal Signal `json:"signal"`
	// Distinct series/streams (head and flushed).
	Series int64 `json:"series"`
	// Unflushed samples/records in the head.
	HeadItems int64 `json:"head_items"`
	// Head buffered bytes.
	HeadBytes int64 `json:"head_bytes"`
	// Flushed immutable parts.
	Parts        int64       `json:"parts"`
	MinTime      OptDateTime `json:"min_time"`
	MaxTime      OptDateTime `json:"max_time"`
	MergeRunning bool        `json:"merge_running"`
	MergeBacklog int64       `json:"merge_backlog"`
	// Whether a write-ahead log is active for this signal.
	Wal         bool  `json:"wal"`
	WalSegments int64 `json:"wal_segments"`
	// Open WAL segment size.
	WalBytes int64 `json:"wal_bytes"`
}

// GetSignal returns the value of Signal.
func (s *EngineSignalStats) GetSignal() Signal {
	return s.Signal
}

// GetSeries returns the value of Series.
func (s *EngineSignalStats) GetSeries() int64 {
	return s.Series
}

// GetHeadItems returns the value of HeadItems.
func (s *EngineSignalStats) GetHeadItems() int64 {
	return s.HeadItems
}

// GetHeadBytes returns the value of HeadBytes.
func (s *EngineSignalStats) GetHeadBytes() int64 {
	return s.HeadBytes
}

// GetParts returns the value of Parts.
func (s *EngineSignalStats) GetParts() int64 {
	return s.Parts
}

// GetMinTime returns the value of MinTime.
func (s *EngineSignalStats) GetMinTime() OptDateTime {
	return s.MinTime
}

// GetMaxTime returns the value of MaxTime.
func (s *EngineSignalStats) GetMaxTime() OptDateTime {
	return s.MaxTime
}

// GetMergeRunning returns the value of MergeRunning.
func (s *EngineSignalStats) GetMergeRunning() bool {
	return s.MergeRunning
}

// GetMergeBacklog returns the value of MergeBacklog.
func (s *EngineSignalStats) GetMergeBacklog() int64 {
	return s.MergeBacklog
}

// GetWal returns the value of Wal.
func (s *EngineSignalStats) GetWal() bool {
	return s.Wal
}

// GetWalSegments returns the value of WalSegments.
func (s *EngineSignalStats) GetWalSegments() int64 {
	return s.WalSegments
}

// GetWalBytes returns the value of WalBytes.
func (s *EngineSignalStats) GetWalBytes() int64 {
	return s.WalBytes
}

// SetSignal sets the value of Signal.
func (s *EngineSignalStats) SetSignal(val Signal) {
	s.Signal = val
}

// SetSeries sets the value of Series.
func (s *EngineSignalStats) SetSeries(val int64) {
	s.Series = val
}

// SetHeadItems sets the value of HeadItems.
func (s *EngineSignalStats) SetHeadItems(val int64) {
	s.HeadItems = val
}

// SetHeadBytes sets the value of HeadBytes.
func (s *EngineSignalStats) SetHeadBytes(val int64) {
	s.HeadBytes = val
}

// SetParts sets the value of Parts.
func (s *EngineSignalStats) SetParts(val int64) {
	s.Parts = val
}

// SetMinTime sets the value of MinTime.
func (s *EngineSignalStats) SetMinTime(val OptDateTime) {
	s.MinTime = val
}

// SetMaxTime sets the value of MaxTime.
func (s *EngineSignalStats) SetMaxTime(val OptDateTime) {
	s.MaxTime = val
}

// SetMergeRunning sets the value of MergeRunning.
func (s *EngineSignalStats) SetMergeRunning(val bool) {
	s.MergeRunning = val
}

// SetMergeBacklog sets the value of MergeBacklog.
func (s *EngineSignalStats) SetMergeBacklog(val int64) {
	s.MergeBacklog = val
}

// SetWal sets the value of Wal.
func (s *EngineSignalStats) SetWal(val bool) {
	s.Wal = val
}

// SetWalSegments sets the value of WalSegments.
func (s *EngineSignalStats) SetWalSegments(val int64) {
	s.WalSegments = val
}

// SetWalBytes sets the value of WalBytes.
func (s *EngineSignalStats) SetWalBytes(val int64) {
	s.WalBytes = val
}

// Embedded oteldb/storage engine statistics.
// Ref: #/components/schemas/EngineStats
type EngineStats struct {
	Tenants     []TenantStats    `json:"tenants"`
	Caches      CacheStats       `json:"caches"`
	Maintenance MaintenanceStats `json:"maintenance"`
	Cluster     OptClusterStats  `json:"cluster"`
}

// GetTenants returns the value of Tenants.
func (s *EngineStats) GetTenants() []TenantStats {
	return s.Tenants
}

// GetCaches returns the value of Caches.
func (s *EngineStats) GetCaches() CacheStats {
	return s.Caches
}

// GetMaintenance returns the value of Maintenance.
func (s *EngineStats) GetMaintenance() MaintenanceStats {
	return s.Maintenance
}

// GetCluster returns the value of Cluster.
func (s *EngineStats) GetCluster() OptClusterStats {
	return s.Cluster
}

// SetTenants sets the value of Tenants.
func (s *EngineStats) SetTenants(val []TenantStats) {
	s.Tenants = val
}

// SetCaches sets the value of Caches.
func (s *EngineStats) SetCaches(val CacheStats) {
	s.Caches = val
}

// SetMaintenance sets the value of Maintenance.
func (s *EngineStats) SetMaintenance(val MaintenanceStats) {
	s.Maintenance = val
}

// SetCluster sets the value of Cluster.
func (s *EngineStats) SetCluster(val OptClusterStats) {
	s.Cluster = val
}

// Error occurred while processing request.
// Ref: #/components/schemas/Error
type Error struct {
	// Human-readable error message.
	ErrorMessage string     `json:"error_message"`
	TraceID      OptTraceID `json:"trace_id"`
	SpanID       OptSpanID  `json:"span_id"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *Error) GetErrorMessage() string {
	return s.ErrorMessage
}

// GetTraceID returns the value of TraceID.
func (s *Error) GetTraceID() OptTraceID {
	return s.TraceID
}

// GetSpanID returns the value of SpanID.
func (s *Error) GetSpanID() OptSpanID {
	return s.SpanID
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *Error) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// SetTraceID sets the value of TraceID.
func (s *Error) SetTraceID(val OptTraceID) {
	s.TraceID = val
}

// SetSpanID sets the value of SpanID.
func (s *Error) SetSpanID(val OptSpanID) {
	s.SpanID = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/HealthReport
type HealthReport struct {
	Status     HealthStatus      `json:"status"`
	Components []ComponentHealth `json:"components"`
}

// GetStatus returns the value of Status.
func (s *HealthReport) GetStatus() HealthStatus {
	return s.Status
}

// GetComponents returns the value of Components.
func (s *HealthReport) GetComponents() []ComponentHealth {
	return s.Components
}

// SetStatus sets the value of Status.
func (s *HealthReport) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetComponents sets the value of Components.
func (s *HealthReport) SetComponents(val []ComponentHealth) {
	s.Components = val
}

// Ref: #/components/schemas/HealthStatus
type HealthStatus string

const (
	HealthStatusHealthy   HealthStatus = "healthy"
	HealthStatusDegraded  HealthStatus = "degraded"
	HealthStatusUnhealthy HealthStatus = "unhealthy"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusHealthy,
		HealthStatusDegraded,
		HealthStatusUnhealthy,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusHealthy:
		return []byte(s), nil
	case HealthStatusDegraded:
		return []byte(s), nil
	case HealthStatusUnhealthy:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusHealthy:
		*s = HealthStatusHealthy
		return nil
	case HealthStatusDegraded:
		*s = HealthStatusDegraded
		return nil
	case HealthStatusUnhealthy:
		*s = HealthStatusUnhealthy
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Instance build info, uptime and per-signal configuration.
// Ref: #/components/schemas/InstanceInfo
type InstanceInfo struct {
	// Build version.
	Version string `json:"version"`
	// VCS commit hash.
	Commit string `json:"commit"`
	// Go toolchain version the binary was built with.
	GoVersion string `json:"go_version"`
	Os        string `json:"os"`
	Arch      string `json:"arch"`
	// Process start time.
	StartTime time.Time `json:"start_time"`
	// Seconds since process start.
	UptimeSeconds float64 `json:"uptime_seconds"`
	// Whether the embedded oteldb/storage engine is active.
	StorageEnabled bool `json:"storage_enabled"`
	// Embedded storage engine backend (memory, file or s3), when enabled.
	StorageBackend OptString `json:"storage_backend"`
	// Whether the (deprecated) ClickHouse storage is active.
	ClickhouseEnabled bool `json:"clickhouse_enabled"`
	// Per-signal configuration.
	Signals []SignalInfo `json:"signals"`
}

// GetVersion returns the value of Version.
func (s *InstanceInfo) GetVersion() string {
	return s.Version
}

// GetCommit returns the value of Commit.
func (s *InstanceInfo) GetCommit() string {
	return s.Commit
}

// GetGoVersion returns the value of GoVersion.
func (s *InstanceInfo) GetGoVersion() string {
	return s.GoVersion
}

// GetOs returns the value of Os.
func (s *InstanceInfo) GetOs() string {
	return s.Os
}

// GetArch returns the value of Arch.
func (s *InstanceInfo) GetArch() string {
	return s.Arch
}

// GetStartTime returns the value of StartTime.
func (s *InstanceInfo) GetStartTime() time.Time {
	return s.StartTime
}

// GetUptimeSeconds returns the value of UptimeSeconds.
func (s *InstanceInfo) GetUptimeSeconds() float64 {
	return s.UptimeSeconds
}

// GetStorageEnabled returns the value of StorageEnabled.
func (s *InstanceInfo) GetStorageEnabled() bool {
	return s.StorageEnabled
}

// GetStorageBackend returns the value of StorageBackend.
func (s *InstanceInfo) GetStorageBackend() OptString {
	return s.StorageBackend
}

// GetClickhouseEnabled returns the value of ClickhouseEnabled.
func (s *InstanceInfo) GetClickhouseEnabled() bool {
	return s.ClickhouseEnabled
}

// GetSignals returns the value of Signals.
func (s *InstanceInfo) GetSignals() []SignalInfo {
	return s.Signals
}

// SetVersion sets the value of Version.
func (s *InstanceInfo) SetVersion(val string) {
	s.Version = val
}

// SetCommit sets the value of Commit.
func (s *InstanceInfo) SetCommit(val string) {
	s.Commit = val
}

// SetGoVersion sets the value of GoVersion.
func (s *InstanceInfo) SetGoVersion(val string) {
	s.GoVersion = val
}

// SetOs sets the value of Os.
func (s *InstanceInfo) SetOs(val string) {
	s.Os = val
}

// SetArch sets the value of Arch.
func (s *InstanceInfo) SetArch(val string) {
	s.Arch = val
}

// SetStartTime sets the value of StartTime.
func (s *InstanceInfo) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetUptimeSeconds sets the value of UptimeSeconds.
func (s *InstanceInfo) SetUptimeSeconds(val float64) {
	s.UptimeSeconds = val
}

// SetStorageEnabled sets the value of StorageEnabled.
func (s *InstanceInfo) SetStorageEnabled(val bool) {
	s.StorageEnabled = val
}

// SetStorageBackend sets the value of StorageBackend.
func (s *InstanceInfo) SetStorageBackend(val OptString) {
	s.StorageBackend = val
}

// SetClickhouseEnabled sets the value of ClickhouseEnabled.
func (s *InstanceInfo) SetClickhouseEnabled(val bool) {
	s.ClickhouseEnabled = val
}

// SetSignals sets the value of Signals.
func (s *InstanceInfo) SetSignals(val []SignalInfo) {
	s.Signals = val
}

// Background maintenance loop liveness and recency. A growing cycle duration means compaction is
// falling behind the ingest rate.
// Ref: #/components/schemas/MaintenanceStats
type MaintenanceStats struct {
	// Completed maintenance cycles since process start (the loop-liveness probe).
	Cycles int64 `json:"cycles"`
	// Start of the most recent cycle, once one has run.
	LastCycleStart OptDateTime `json:"last_cycle_start"`
	// Duration of the most recent completed cycle.
	LastCycleDurationSeconds float64 `json:"last_cycle_duration_seconds"`
	// Engine tasks (flush/merge or replica refresh) dispatched in the most recent cycle.
	LastCycleTasks int64 `json:"last_cycle_tasks"`
}

// GetCycles returns the value of Cycles.
func (s *MaintenanceStats) GetCycles() int64 {
	return s.Cycles
}

// GetLastCycleStart returns the value of LastCycleStart.
func (s *MaintenanceStats) GetLastCycleStart() OptDateTime {
	return s.LastCycleStart
}

// GetLastCycleDurationSeconds returns the value of LastCycleDurationSeconds.
func (s *MaintenanceStats) GetLastCycleDurationSeconds() float64 {
	return s.LastCycleDurationSeconds
}

// GetLastCycleTasks returns the value of LastCycleTasks.
func (s *MaintenanceStats) GetLastCycleTasks() int64 {
	return s.LastCycleTasks
}

// SetCycles sets the value of Cycles.
func (s *MaintenanceStats) SetCycles(val int64) {
	s.Cycles = val
}

// SetLastCycleStart sets the value of LastCycleStart.
func (s *MaintenanceStats) SetLastCycleStart(val OptDateTime) {
	s.LastCycleStart = val
}

// SetLastCycleDurationSeconds sets the value of LastCycleDurationSeconds.
func (s *MaintenanceStats) SetLastCycleDurationSeconds(val float64) {
	s.LastCycleDurationSeconds = val
}

// SetLastCycleTasks sets the value of LastCycleTasks.
func (s *MaintenanceStats) SetLastCycleTasks(val int64) {
	s.LastCycleTasks = val
}

// NewOptClickHouseStats returns new OptClickHouseStats with value set to v.
func NewOptClickHouseStats(v ClickHouseStats) OptClickHouseStats {
	return OptClickHouseStats{
		Value: v,
		Set:   true,
	}
}

// OptClickHouseStats is optional ClickHouseStats.
type OptClickHouseStats struct {
	Value ClickHouseStats
	Set   bool
}

// IsSet returns true if OptClickHouseStats was set.
func (o OptClickHouseStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptClickHouseStats) Reset() {
	var v ClickHouseStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptClickHouseStats) SetTo(v ClickHouseStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptClickHouseStats) Get() (v ClickHouseStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptClickHouseStats) Or(d ClickHouseStats) ClickHouseStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptClusterStats returns new OptClusterStats with value set to v.
func NewOptClusterStats(v ClusterStats) OptClusterStats {
	return OptClusterStats{
		Value: v,
		Set:   true,
	}
}

// OptClusterStats is optional ClusterStats.
type OptClusterStats struct {
	Value ClusterStats
	Set   bool
}

// IsSet returns true if OptClusterStats was set.
func (o OptClusterStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptClusterStats) Reset() {
	var v ClusterStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptClusterStats) SetTo(v ClusterStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptClusterStats) Get() (v ClusterStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptClusterStats) Or(d ClusterStats) ClusterStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptECStats returns new OptECStats with value set to v.
func NewOptECStats(v ECStats) OptECStats {
	return OptECStats{
		Value: v,
		Set:   true,
	}
}

// OptECStats is optional ECStats.
type OptECStats struct {
	Value ECStats
	Set   bool
}

// IsSet returns true if OptECStats was set.
func (o OptECStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptECStats) Reset() {
	var v ECStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptECStats) SetTo(v ECStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptECStats) Get() (v ECStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptECStats) Or(d ECStats) ECStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEngineStats returns new OptEngineStats with value set to v.
func NewOptEngineStats(v EngineStats) OptEngineStats {
	return OptEngineStats{
		Value: v,
		Set:   true,
	}
}

// OptEngineStats is optional EngineStats.
type OptEngineStats struct {
	Value EngineStats
	Set   bool
}

// IsSet returns true if OptEngineStats was set.
func (o OptEngineStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEngineStats) Reset() {
	var v EngineStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEngineStats) SetTo(v EngineStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEngineStats) Get() (v EngineStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEngineStats) Or(d EngineStats) EngineStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPartSyncStats returns new OptPartSyncStats with value set to v.
func NewOptPartSyncStats(v PartSyncStats) OptPartSyncStats {
	return OptPartSyncStats{
		Value: v,
		Set:   true,
	}
}

// OptPartSyncStats is optional PartSyncStats.
type OptPartSyncStats struct {
	Value PartSyncStats
	Set   bool
}

// IsSet returns true if OptPartSyncStats was set.
func (o OptPartSyncStats) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPartSyncStats) Reset() {
	var v PartSyncStats
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPartSyncStats) SetTo(v PartSyncStats) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPartSyncStats) Get() (v PartSyncStats, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPartSyncStats) Or(d PartSyncStats) PartSyncStats {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSpanID returns new OptSpanID with value set to v.
func NewOptSpanID(v SpanID) OptSpanID {
	return OptSpanID{
		Value: v,
		Set:   true,
	}
}

// OptSpanID is optional SpanID.
type OptSpanID struct {
	Value SpanID
	Set   bool
}

// IsSet returns true if OptSpanID was set.
func (o OptSpanID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSpanID) Reset() {
	var v SpanID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSpanID) SetTo(v SpanID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSpanID) Get() (v SpanID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSpanID) Or(d SpanID) SpanID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTraceID returns new OptTraceID with value set to v.
func NewOptTraceID(v TraceID) OptTraceID {
	return OptTraceID{
		Value: v,
		Set:   true,
	}
}

// OptTraceID is optional TraceID.
type OptTraceID struct {
	Value TraceID
	Set   bool
}

// IsSet returns true if OptTraceID was set.
func (o OptTraceID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTraceID) Reset() {
	var v TraceID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTraceID) SetTo(v TraceID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTraceID) Get() (v TraceID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTraceID) Or(d TraceID) TraceID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Cumulative shared-nothing part-mirroring activity of this node, present only when the cluster runs
// with a private (per-node) backend.
// Ref: #/components/schemas/PartSyncStats
type PartSyncStats struct {
	// Sync attempts including no-ops (the sync-loop liveness probe).
	Passes int64 `json:"passes"`
	// Passes that installed a newer peer copy.
	Mirrored int64 `json:"mirrored"`
	// Objects fetched from peers.
	Copied int64 `json:"copied"`
	// Total size of objects fetched from peers.
	CopiedBytes int64 `json:"copied_bytes"`
	// Stale local objects deleted after the quarantine delay.
	Pruned int64 `json:"pruned"`
	// Passes that failed part-way (retried next maintenance tick).
	Errors int64 `json:"errors"`
	// When the last mirroring pass completed (the replication-staleness probe).
	LastSync OptDateTime `json:"last_sync"`
}

// GetPasses returns the value of Passes.
func (s *PartSyncStats) GetPasses() int64 {
	return s.Passes
}

// GetMirrored returns the value of Mirrored.
func (s *PartSyncStats) GetMirrored() int64 {
	return s.Mirrored
}

// GetCopied returns the value of Copied.
func (s *PartSyncStats) GetCopied() int64 {
	return s.Copied
}

// GetCopiedBytes returns the value of CopiedBytes.
func (s *PartSyncStats) GetCopiedBytes() int64 {
	return s.CopiedBytes
}

// GetPruned returns the value of Pruned.
func (s *PartSyncStats) GetPruned() int64 {
	return s.Pruned
}

// GetErrors returns the value of Errors.
func (s *PartSyncStats) GetErrors() int64 {
	return s.Errors
}

// GetLastSync returns the value of LastSync.
func (s *PartSyncStats) GetLastSync() OptDateTime {
	return s.LastSync
}

// SetPasses sets the value of Passes.
func (s *PartSyncStats) SetPasses(val int64) {
	s.Passes = val
}

// SetMirrored sets the value of Mirrored.
func (s *PartSyncStats) SetMirrored(val int64) {
	s.Mirrored = val
}

// SetCopied sets the value of Copied.
func (s *PartSyncStats) SetCopied(val int64) {
	s.Copied = val
}

// SetCopiedBytes sets the value of CopiedBytes.
func (s *PartSyncStats) SetCopiedBytes(val int64) {
	s.CopiedBytes = val
}

// SetPruned sets the value of Pruned.
func (s *PartSyncStats) SetPruned(val int64) {
	s.Pruned = val
}

// SetErrors sets the value of Errors.
func (s *PartSyncStats) SetErrors(val int64) {
	s.Errors = val
}

// SetLastSync sets the value of LastSync.
func (s *PartSyncStats) SetLastSync(val OptDateTime) {
	s.LastSync = val
}

// Ref: #/components/schemas/RuntimeStats
type RuntimeStats struct {
	Goroutines int64 `json:"goroutines"`
	NumCPU     int   `json:"num_cpu"`
	Gomaxprocs int   `json:"gomaxprocs"`
	// Bytes of allocated heap objects (live heap).
	HeapAllocBytes  int64 `json:"heap_alloc_bytes"`
	HeapInuseBytes  int64 `json:"heap_inuse_bytes"`
	HeapSysBytes    int64 `json:"heap_sys_bytes"`
	StackInuseBytes int64 `json:"stack_inuse_bytes"`
	// Number of completed GC cycles.
	GcCount int64 `json:"gc_count"`
	// Target heap size of the next GC cycle.
	NextGcBytes int64 `json:"next_gc_bytes"`
	// Soft memory limit (GOMEMLIMIT), when set.
	MemLimitBytes OptInt64 `json:"mem_limit_bytes"`
}

// GetGoroutines returns the value of Goroutines.
func (s *RuntimeStats) GetGoroutines() int64 {
	return s.Goroutines
}

// GetNumCPU returns the value of NumCPU.
func (s *RuntimeStats) GetNumCPU() int {
	return s.NumCPU
}

// GetGomaxprocs returns the value of Gomaxprocs.
func (s *RuntimeStats) GetGomaxprocs() int {
	return s.Gomaxprocs
}

// GetHeapAllocBytes returns the value of HeapAllocBytes.
func (s *RuntimeStats) GetHeapAllocBytes() int64 {
	return s.HeapAllocBytes
}

// GetHeapInuseBytes returns the value of HeapInuseBytes.
func (s *RuntimeStats) GetHeapInuseBytes() int64 {
	return s.HeapInuseBytes
}

// GetHeapSysBytes returns the value of HeapSysBytes.
func (s *RuntimeStats) GetHeapSysBytes() int64 {
	return s.HeapSysBytes
}

// GetStackInuseBytes returns the value of StackInuseBytes.
func (s *RuntimeStats) GetStackInuseBytes() int64 {
	return s.StackInuseBytes
}

// GetGcCount returns the value of GcCount.
func (s *RuntimeStats) GetGcCount() int64 {
	return s.GcCount
}

// GetNextGcBytes returns the value of NextGcBytes.
func (s *RuntimeStats) GetNextGcBytes() int64 {
	return s.NextGcBytes
}

// GetMemLimitBytes returns the value of MemLimitBytes.
func (s *RuntimeStats) GetMemLimitBytes() OptInt64 {
	return s.MemLimitBytes
}

// SetGoroutines sets the value of Goroutines.
func (s *RuntimeStats) SetGoroutines(val int64) {
	s.Goroutines = val
}

// SetNumCPU sets the value of NumCPU.
func (s *RuntimeStats) SetNumCPU(val int) {
	s.NumCPU = val
}

// SetGomaxprocs sets the value of Gomaxprocs.
func (s *RuntimeStats) SetGomaxprocs(val int) {
	s.Gomaxprocs = val
}

// SetHeapAllocBytes sets the value of HeapAllocBytes.
func (s *RuntimeStats) SetHeapAllocBytes(val int64) {
	s.HeapAllocBytes = val
}

// SetHeapInuseBytes sets the value of HeapInuseBytes.
func (s *RuntimeStats) SetHeapInuseBytes(val int64) {
	s.HeapInuseBytes = val
}

// SetHeapSysBytes sets the value of HeapSysBytes.
func (s *RuntimeStats) SetHeapSysBytes(val int64) {
	s.HeapSysBytes = val
}

// SetStackInuseBytes sets the value of StackInuseBytes.
func (s *RuntimeStats) SetStackInuseBytes(val int64) {
	s.StackInuseBytes = val
}

// SetGcCount sets the value of GcCount.
func (s *RuntimeStats) SetGcCount(val int64) {
	s.GcCount = val
}

// SetNextGcBytes sets the value of NextGcBytes.
func (s *RuntimeStats) SetNextGcBytes(val int64) {
	s.NextGcBytes = val
}

// SetMemLimitBytes sets the value of MemLimitBytes.
func (s *RuntimeStats) SetMemLimitBytes(val OptInt64) {
	s.MemLimitBytes = val
}

// Telemetry signal.
// Ref: #/components/schemas/Signal
type Signal string

const (
	SignalMetrics  Signal = "metrics"
	SignalTraces   Signal = "traces"
	SignalLogs     Signal = "logs"
	SignalProfiles Signal = "profiles"
)

// AllValues returns all Signal values.
func (Signal) AllValues() []Signal {
	return []Signal{
		SignalMetrics,
		SignalTraces,
		SignalLogs,
		SignalProfiles,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Signal) MarshalText() ([]byte, error) {
	switch s {
	case SignalMetrics:
		return []byte(s), nil
	case SignalTraces:
		return []byte(s), nil
	case SignalLogs:
		return []byte(s), nil
	case SignalProfiles:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Signal) UnmarshalText(data []byte) error {
	switch Signal(data) {
	case SignalMetrics:
		*s = SignalMetrics
		return nil
	case SignalTraces:
		*s = SignalTraces
		return nil
	case SignalLogs:
		*s = SignalLogs
		return nil
	case SignalProfiles:
		*s = SignalProfiles
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// One (tenant, signal)'s flushed-data shape: how many points it stores, in how many bytes, and how
// well they compress. Stored bytes are this node's on-disk footprint — under erasure coding with
// slot filtering that is the local shard, not the cluster-wide total.
// Ref: #/components/schemas/SignalEfficiency
type SignalEfficiency struct {
	Signal Signal `json:"signal"`
	// Distinct series/streams (head and flushed).
	Series int64 `json:"series"`
	// Flushed part count.
	Parts int64 `json:"parts"`
	// Total samples (metrics) or records (logs/traces/profiles).
	Points int64 `json:"points"`
	// Sum of the parts' backend object sizes on this node.
	StoredBytes int64 `json:"stored_bytes"`
	// Stored bytes per point — the per-sample storage cost.
	BytesPerPoint float64 `json:"bytes_per_point"`
	// Uncompressed logical size of the stored points; present only for metrics (points x 16), the record
	// signals' per-record logical size is not recorded.
	LogicalBytes OptInt64 `json:"logical_bytes"`
	// Logical/stored ratio (e.g. 8.0 = stored at 1/8th of logical); present only when logical size is
	// known.
	CompressionRatio OptFloat64 `json:"compression_ratio"`
}

// GetSignal returns the value of Signal.
func (s *SignalEfficiency) GetSignal() Signal {
	return s.Signal
}

// GetSeries returns the value of Series.
func (s *SignalEfficiency) GetSeries() int64 {
	return s.Series
}

// GetParts returns the value of Parts.
func (s *SignalEfficiency) GetParts() int64 {
	return s.Parts
}

// GetPoints returns the value of Points.
func (s *SignalEfficiency) GetPoints() int64 {
	return s.Points
}

// GetStoredBytes returns the value of StoredBytes.
func (s *SignalEfficiency) GetStoredBytes() int64 {
	return s.StoredBytes
}

// GetBytesPerPoint returns the value of BytesPerPoint.
func (s *SignalEfficiency) GetBytesPerPoint() float64 {
	return s.BytesPerPoint
}

// GetLogicalBytes returns the value of LogicalBytes.
func (s *SignalEfficiency) GetLogicalBytes() OptInt64 {
	return s.LogicalBytes
}

// GetCompressionRatio returns the value of CompressionRatio.
func (s *SignalEfficiency) GetCompressionRatio() OptFloat64 {
	return s.CompressionRatio
}

// SetSignal sets the value of Signal.
func (s *SignalEfficiency) SetSignal(val Signal) {
	s.Signal = val
}

// SetSeries sets the value of Series.
func (s *SignalEfficiency) SetSeries(val int64) {
	s.Series = val
}

// SetParts sets the value of Parts.
func (s *SignalEfficiency) SetParts(val int64) {
	s.Parts = val
}

// SetPoints sets the value of Points.
func (s *SignalEfficiency) SetPoints(val int64) {
	s.Points = val
}

// SetStoredBytes sets the value of StoredBytes.
func (s *SignalEfficiency) SetStoredBytes(val int64) {
	s.StoredBytes = val
}

// SetBytesPerPoint sets the value of BytesPerPoint.
func (s *SignalEfficiency) SetBytesPerPoint(val float64) {
	s.BytesPerPoint = val
}

// SetLogicalBytes sets the value of LogicalBytes.
func (s *SignalEfficiency) SetLogicalBytes(val OptInt64) {
	s.LogicalBytes = val
}

// SetCompressionRatio sets the value of CompressionRatio.
func (s *SignalEfficiency) SetCompressionRatio(val OptFloat64) {
	s.CompressionRatio = val
}

// Ref: #/components/schemas/SignalInfo
type SignalInfo struct {
	Signal Signal `json:"signal"`
	// Storage backend serving this signal (clickhouse, storage or none).
	Backend string `json:"backend"`
	// Whether a query API is wired for this signal.
	Queryable bool `json:"queryable"`
	// Listen address of the signal's query API, when queryable.
	Bind OptString `json:"bind"`
}

// GetSignal returns the value of Signal.
func (s *SignalInfo) GetSignal() Signal {
	return s.Signal
}

// GetBackend returns the value of Backend.
func (s *SignalInfo) GetBackend() string {
	return s.Backend
}

// GetQueryable returns the value of Queryable.
func (s *SignalInfo) GetQueryable() bool {
	return s.Queryable
}

// GetBind returns the value of Bind.
func (s *SignalInfo) GetBind() OptString {
	return s.Bind
}

// SetSignal sets the value of Signal.
func (s *SignalInfo) SetSignal(val Signal) {
	s.Signal = val
}

// SetBackend sets the value of Backend.
func (s *SignalInfo) SetBackend(val string) {
	s.Backend = val
}

// SetQueryable sets the value of Queryable.
func (s *SignalInfo) SetQueryable(val bool) {
	s.Queryable = val
}

// SetBind sets the value of Bind.
func (s *SignalInfo) SetBind(val OptString) {
	s.Bind = val
}

type SpanID string

// Storage statistics for the embedded engine (primary) and ClickHouse (deprecated).
// Ref: #/components/schemas/StorageStats
type StorageStats struct {
	// Whether the embedded oteldb/storage engine is active.
	StorageEnabled bool `json:"storage_enabled"`
	// Whether the (deprecated) ClickHouse storage is active.
	ClickhouseEnabled bool               `json:"clickhouse_enabled"`
	Engine            OptEngineStats     `json:"engine"`
	Clickhouse        OptClickHouseStats `json:"clickhouse"`
}

// GetStorageEnabled returns the value of StorageEnabled.
func (s *StorageStats) GetStorageEnabled() bool {
	return s.StorageEnabled
}

// GetClickhouseEnabled returns the value of ClickhouseEnabled.
func (s *StorageStats) GetClickhouseEnabled() bool {
	return s.ClickhouseEnabled
}

// GetEngine returns the value of Engine.
func (s *StorageStats) GetEngine() OptEngineStats {
	return s.Engine
}

// GetClickhouse returns the value of Clickhouse.
func (s *StorageStats) GetClickhouse() OptClickHouseStats {
	return s.Clickhouse
}

// SetStorageEnabled sets the value of StorageEnabled.
func (s *StorageStats) SetStorageEnabled(val bool) {
	s.StorageEnabled = val
}

// SetClickhouseEnabled sets the value of ClickhouseEnabled.
func (s *StorageStats) SetClickhouseEnabled(val bool) {
	s.ClickhouseEnabled = val
}

// SetEngine sets the value of Engine.
func (s *StorageStats) SetEngine(val OptEngineStats) {
	s.Engine = val
}

// SetClickhouse sets the value of Clickhouse.
func (s *StorageStats) SetClickhouse(val OptClickHouseStats) {
	s.Clickhouse = val
}

// Ref: #/components/schemas/TableStats
type TableStats struct {
	Database string `json:"database"`
	Table    string `json:"table"`
	Rows     int64  `json:"rows"`
	// Compressed on-disk size.
	BytesOnDisk           int64 `json:"bytes_on_disk"`
	DataUncompressedBytes int64 `json:"data_uncompressed_bytes"`
	// Number of active parts.
	Parts int64 `json:"parts"`
	// Earliest partition time, when available.
	MinTime OptDateTime `json:"min_time"`
	// Latest partition time, when available.
	MaxTime OptDateTime `json:"max_time"`
}

// GetDatabase returns the value of Database.
func (s *TableStats) GetDatabase() string {
	return s.Database
}

// GetTable returns the value of Table.
func (s *TableStats) GetTable() string {
	return s.Table
}

// GetRows returns the value of Rows.
func (s *TableStats) GetRows() int64 {
	return s.Rows
}

// GetBytesOnDisk returns the value of BytesOnDisk.
func (s *TableStats) GetBytesOnDisk() int64 {
	return s.BytesOnDisk
}

// GetDataUncompressedBytes returns the value of DataUncompressedBytes.
func (s *TableStats) GetDataUncompressedBytes() int64 {
	return s.DataUncompressedBytes
}

// GetParts returns the value of Parts.
func (s *TableStats) GetParts() int64 {
	return s.Parts
}

// GetMinTime returns the value of MinTime.
func (s *TableStats) GetMinTime() OptDateTime {
	return s.MinTime
}

// GetMaxTime returns the value of MaxTime.
func (s *TableStats) GetMaxTime() OptDateTime {
	return s.MaxTime
}

// SetDatabase sets the value of Database.
func (s *TableStats) SetDatabase(val string) {
	s.Database = val
}

// SetTable sets the value of Table.
func (s *TableStats) SetTable(val string) {
	s.Table = val
}

// SetRows sets the value of Rows.
func (s *TableStats) SetRows(val int64) {
	s.Rows = val
}

// SetBytesOnDisk sets the value of BytesOnDisk.
func (s *TableStats) SetBytesOnDisk(val int64) {
	s.BytesOnDisk = val
}

// SetDataUncompressedBytes sets the value of DataUncompressedBytes.
func (s *TableStats) SetDataUncompressedBytes(val int64) {
	s.DataUncompressedBytes = val
}

// SetParts sets the value of Parts.
func (s *TableStats) SetParts(val int64) {
	s.Parts = val
}

// SetMinTime sets the value of MinTime.
func (s *TableStats) SetMinTime(val OptDateTime) {
	s.MinTime = val
}

// SetMaxTime sets the value of MaxTime.
func (s *TableStats) SetMaxTime(val OptDateTime) {
	s.MaxTime = val
}

// One tenant's per-signal efficiency breakdown.
// Ref: #/components/schemas/TenantEfficiency
type TenantEfficiency struct {
	// Tenant identifier.
	Tenant  string             `json:"tenant"`
	Signals []SignalEfficiency `json:"signals"`
}

// GetTenant returns the value of Tenant.
func (s *TenantEfficiency) GetTenant() string {
	return s.Tenant
}

// GetSignals returns the value of Signals.
func (s *TenantEfficiency) GetSignals() []SignalEfficiency {
	return s.Signals
}

// SetTenant sets the value of Tenant.
func (s *TenantEfficiency) SetTenant(val string) {
	s.Tenant = val
}

// SetSignals sets the value of Signals.
func (s *TenantEfficiency) SetSignals(val []SignalEfficiency) {
	s.Signals = val
}

// Ref: #/components/schemas/TenantStats
type TenantStats struct {
	// Tenant identifier.
	Tenant string `json:"tenant"`
	// Sum of series across all signals.
	TotalSeries int64 `json:"total_series"`
	// Sum of flushed parts across all signals.
	TotalParts int64               `json:"total_parts"`
	Admission  AdmissionStats      `json:"admission"`
	Signals    []EngineSignalStats `json:"signals"`
}

// GetTenant returns the value of Tenant.
func (s *TenantStats) GetTenant() string {
	return s.Tenant
}

// GetTotalSeries returns the value of TotalSeries.
func (s *TenantStats) GetTotalSeries() int64 {
	return s.TotalSeries
}

// GetTotalParts returns the value of TotalParts.
func (s *TenantStats) GetTotalParts() int64 {
	return s.TotalParts
}

// GetAdmission returns the value of Admission.
func (s *TenantStats) GetAdmission() AdmissionStats {
	return s.Admission
}

// GetSignals returns the value of Signals.
func (s *TenantStats) GetSignals() []EngineSignalStats {
	return s.Signals
}

// SetTenant sets the value of Tenant.
func (s *TenantStats) SetTenant(val string) {
	s.Tenant = val
}

// SetTotalSeries sets the value of TotalSeries.
func (s *TenantStats) SetTotalSeries(val int64) {
	s.TotalSeries = val
}

// SetTotalParts sets the value of TotalParts.
func (s *TenantStats) SetTotalParts(val int64) {
	s.TotalParts = val
}

// SetAdmission sets the value of Admission.
func (s *TenantStats) SetAdmission(val AdmissionStats) {
	s.Admission = val
}

// SetSignals sets the value of Signals.
func (s *TenantStats) SetSignals(val []EngineSignalStats) {
	s.Signals = val
}

type TraceID string
