// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements getHealth operation.
//
// Health of each wired service (query APIs, collector, storage).
//
// GET /api/v1/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *HealthReport, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInfo implements getInfo operation.
//
// Build information, uptime and per-signal backend configuration.
//
// GET /api/v1/info
func (UnimplementedHandler) GetInfo(ctx context.Context) (r *InstanceInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRuntime implements getRuntime operation.
//
// Live heap, GC and goroutine counters of the running process.
//
// GET /api/v1/runtime
func (UnimplementedHandler) GetRuntime(ctx context.Context) (r *RuntimeStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorage implements getStorage operation.
//
// Per-table statistics (rows, on-disk and uncompressed bytes, parts, min/max timestamp) collected from
// ClickHouse system tables. Empty when no signal is served from ClickHouse.
//
// GET /api/v1/storage
func (UnimplementedHandler) GetStorage(ctx context.Context) (r *StorageStats, _ error) {
	return r, ht.ErrNotImplemented
}

// RunAction implements runAction operation.
//
// Execute a maintenance action against the running process.
//
// POST /api/v1/actions/{action}
func (UnimplementedHandler) RunAction(ctx context.Context, params RunActionParams) (r *ActionResult, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
