// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// RunActionParams is parameters of runAction operation.
type RunActionParams struct {
	// Action to run.
	Action ActionName
}

func unpackRunActionParams(packed middleware.Parameters) (params RunActionParams) {
	{
		key := middleware.ParameterKey{
			Name: "action",
			In:   "path",
		}
		params.Action = packed[key].(ActionName)
	}
	return params
}

func decodeRunActionParams(args [1]string, argsEscaped bool, r *http.Request) (params RunActionParams, _ error) {
	// Decode path: action.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "action",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Action = ActionName(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Action.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "action",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
