// Code generated by ogen, DO NOT EDIT.

package adminapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthOperation  OperationName = "GetHealth"
	GetInfoOperation    OperationName = "GetInfo"
	GetRuntimeOperation OperationName = "GetRuntime"
	GetStorageOperation OperationName = "GetStorage"
	RunActionOperation  OperationName = "RunAction"
)
