version: 2
project_name: oteldb

builds:
  - id: oteldb
    binary: "oteldb{{ .Ext }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/oteldb
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: chotel
    binary: "chotel{{ .Ext }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/chotel
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: odbbackup
    binary: "odbbackup{{ .Ext }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/odbbackup
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: odbrestore
    binary: "odbrestore{{ .Ext }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/odbrestore
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

  - id: docker-logql
    binary: "docker-logql{{ .Ext }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/docker-logql
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch  }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

release:
  # prerelease: allow # remove this when we start publishing non-prerelease or set to auto
  # draft: true # allow for manual edits
  github:
    owner: oteldb
    name: oteldb

  mode: replace
  draft: false
  prerelease: auto

  # Templates: allowed
  footer: |
    ## Docker images

    ```
    {{ .Env.IMAGE }}:v{{ .Version }}
    ```

dockers_v2:
  - id: ubuntu
    images:
      - "ghcr.io/oteldb/oteldb"

    dockerfile: release.Dockerfile

    # Keep tag in sync with produced images tags.
    build_args:
      BASE_IMAGE: "ubuntu:questing"

    platforms:
      - linux/amd64
      - linux/arm64

    tags:
      - "{{ if not .IsNightly }}latest{{ end }}"
      - "{{ if not .IsNightly }}latest-ubuntu{{ end }}"
      - "{{ if not .IsNightly }}ubuntu{{ end }}"
      - "{{ if not .IsNightly }}questing{{ end }}"
      - "v{{ .Version }}"
      - "v{{ .Version }}-ubuntu"
      - "v{{ .Version }}-questing"
      - "{{ if .IsNightly }}nightly-ubuntu{{ end }}"
      - "{{ if .IsNightly }}nightly-questing{{ end }}"

    labels:
      "io.artifacthub.package.readme-url": "https://github.com/oteldb/oteldb/blob/main/README.md"
      "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/131437363"
      "io.artifacthub.package.maintainers": '[{"name":"Aleksandr Razumov","email":"ernado@go-faster.org"}]'
      "io.artifacthub.package.license": "Apache 2.0"

      "org.opencontainers.image.description": "OpenTelemetry signal storage"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

  - id: distroless
    images:
      - "ghcr.io/oteldb/oteldb"

    dockerfile: release.Dockerfile

    build_args:
      BASE_IMAGE: "gcr.io/distroless/static"

    platforms:
      - linux/amd64
      - linux/arm64

    tags:
      - "{{ if not .IsNightly }}distroless{{ end }}"
      - "v{{ .Version }}-distroless"
      - "{{ if .IsNightly }}nightly-distroless{{ end }}"

    labels:
      "io.artifacthub.package.readme-url": "https://github.com/oteldb/oteldb/blob/main/README.md"
      "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/131437363"
      "io.artifacthub.package.maintainers": '[{"name":"Aleksandr Razumov","email":"ernado@go-faster.org"}]'
      "io.artifacthub.package.license": "Apache 2.0"

      "org.opencontainers.image.description": "OpenTelemetry signal storage"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

  - id: distroless-chotel
    images:
      - "ghcr.io/oteldb/oteldb/chotel"

    dockerfile: release.Dockerfile

    build_args:
      BASE_IMAGE: "gcr.io/distroless/static"

    platforms:
      - linux/amd64
      - linux/arm64

    tags:
      - "{{ if not .IsNightly }}latest{{ end }}"
      - "{{ if not .IsNightly }}distroless{{ end }}"
      - "v{{ .Version }}"
      - "v{{ .Version }}-distroless"
      - "{{ if .IsNightly }}nightly-distroless{{ end }}"

    labels:
      "io.artifacthub.package.readme-url": "https://github.com/oteldb/oteldb/blob/main/README.md"
      "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/131437363"
      "io.artifacthub.package.maintainers": '[{"name":"Aleksandr Razumov","email":"ernado@go-faster.org"}]'
      "io.artifacthub.package.license": "Apache 2.0"

      "org.opencontainers.image.description": "OpenTelemetry signal storage"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "Helm chart updates"
      order: 700
      regexp: '^.*?(feat|fix|chore)\(helm\)!?:.+$'
    - title: "Dependency updates"
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(\S+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(\S+\))??!?:.+$'
      order: 150
    - title: "Performance updates"
      regexp: '^.*?perf(\(\S+\))??!?:.+$'
      order: 250
    - title: "Bug fixes"
      regexp: '^.*?fix(\(\S+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: '^.*?docs(\(\S+\))??!?:.+$'
      order: 400
    - title: "Benchmarking tooling changes"
      regexp: '^.*?(\(\S*bench\S*\))!?:.+$'
      order: 450
    - title: "Build process updates"
      regexp: '^.*?build(\(\S+\))??!?:.+$'
      order: 500
    - title: "CI/CD updates"
      regexp: '^.*?ci(\(\S+\))??!?:.+$'
      order: 600
    - title: "Updates to tests"
      regexp: '^.*?test(\(\S+\))??!?:.+$'
      order: 600

    - title: Other work
      order: 9999

sboms:
  - artifacts: archive

nfpms:
  - id: oteldb
    package_name: oteldb
    ids:
      - oteldb
      - chotel
      - odbbackup
      - odbrestore
    homepage: https://github.com/oteldb/oteldb
    maintainer: Aleksandr Razumov <ernado@go-faster.org>
    description: OpenTelemetry signal storage
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
  - id: docker-logql
    package_name: docker-logql
    ids:
      - docker-logql
    homepage: https://github.com/oteldb/oteldb/tree/main/cmd/docker-logql
    maintainer: Aleksandr Razumov <ernado@go-faster.org>
    description: A simple Docker CLI plugin to run LogQL queries over container logs.
    license: Apache 2.0
    # Install to /usr/lib/docker/cli-plugins, as it would be expected by Docker CLI.
    bindir: /usr/lib/docker/cli-plugins
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
