/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActionName,
  ActionResult,
  ClusterStorage,
  EfficiencyStats,
  ErrorResponse,
  GetEfficiencyParams,
  GetStreamCostsParams,
  HealthReport,
  InstanceInfo,
  RuntimeStats,
  StorageStats,
  StreamCosts
} from './model';

import { customFetch } from '../lib/fetcher';




/**
 * Build information, uptime and per-signal backend configuration.
 * @summary Instance info and effective config
 */
export const getInfo = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<InstanceInfo>(
      {url: `/api/v1/info`, method: 'GET', signal
    },
      );
    }
  



export const getGetInfoQueryKey = () => {
    return [
    `/api/v1/info`
    ] as const;
    }

    
export const getGetInfoQueryOptions = <TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInfo>>> = ({ signal }) => getInfo(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>
export type GetInfoQueryError = ErrorResponse


export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfo>>,
          TError,
          Awaited<ReturnType<typeof getInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfo>>,
          TError,
          Awaited<ReturnType<typeof getInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Instance info and effective config
 */

export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Health of each wired service (query APIs, collector, storage).
 * @summary Component health
 */
export const getHealth = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<HealthReport>(
      {url: `/api/v1/health`, method: 'GET', signal
    },
      );
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = ErrorResponse


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Component health
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Live heap, GC and goroutine counters of the running process.
 * @summary Go runtime statistics
 */
export const getRuntime = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<RuntimeStats>(
      {url: `/api/v1/runtime`, method: 'GET', signal
    },
      );
    }
  



export const getGetRuntimeQueryKey = () => {
    return [
    `/api/v1/runtime`
    ] as const;
    }

    
export const getGetRuntimeQueryOptions = <TData = Awaited<ReturnType<typeof getRuntime>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRuntimeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRuntime>>> = ({ signal }) => getRuntime(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRuntimeQueryResult = NonNullable<Awaited<ReturnType<typeof getRuntime>>>
export type GetRuntimeQueryError = ErrorResponse


export function useGetRuntime<TData = Awaited<ReturnType<typeof getRuntime>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRuntime>>,
          TError,
          Awaited<ReturnType<typeof getRuntime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRuntime<TData = Awaited<ReturnType<typeof getRuntime>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRuntime>>,
          TError,
          Awaited<ReturnType<typeof getRuntime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRuntime<TData = Awaited<ReturnType<typeof getRuntime>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Go runtime statistics
 */

export function useGetRuntime<TData = Awaited<ReturnType<typeof getRuntime>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRuntime>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRuntimeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Per-table statistics (rows, on-disk and uncompressed bytes, parts, min/max timestamp) collected from ClickHouse system tables. Empty when no signal is served from ClickHouse.

 * @summary ClickHouse storage statistics
 */
export const getStorage = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<StorageStats>(
      {url: `/api/v1/storage`, method: 'GET', signal
    },
      );
    }
  



export const getGetStorageQueryKey = () => {
    return [
    `/api/v1/storage`
    ] as const;
    }

    
export const getGetStorageQueryOptions = <TData = Awaited<ReturnType<typeof getStorage>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStorageQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStorage>>> = ({ signal }) => getStorage(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStorageQueryResult = NonNullable<Awaited<ReturnType<typeof getStorage>>>
export type GetStorageQueryError = ErrorResponse


export function useGetStorage<TData = Awaited<ReturnType<typeof getStorage>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorage>>,
          TError,
          Awaited<ReturnType<typeof getStorage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorage<TData = Awaited<ReturnType<typeof getStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorage>>,
          TError,
          Awaited<ReturnType<typeof getStorage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorage<TData = Awaited<ReturnType<typeof getStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ClickHouse storage statistics
 */

export function useGetStorage<TData = Awaited<ReturnType<typeof getStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStorageQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Per-tenant, per-signal capacity and efficiency breakdown of the embedded storage engine: series, parts, points, stored bytes, bytes per point and compression ratios. Unlike the other storage endpoints this one performs backend I/O (per-part object sizes) — poll it at dashboard cadence, not per request. Empty when the embedded engine is not active.

 * @summary Embedded storage efficiency statistics
 */
export const getEfficiency = (
    params?: GetEfficiencyParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<EfficiencyStats>(
      {url: `/api/v1/storage/efficiency`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetEfficiencyQueryKey = (params?: GetEfficiencyParams,) => {
    return [
    `/api/v1/storage/efficiency`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetEfficiencyQueryOptions = <TData = Awaited<ReturnType<typeof getEfficiency>>, TError = ErrorResponse>(params?: GetEfficiencyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEfficiencyQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEfficiency>>> = ({ signal }) => getEfficiency(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEfficiencyQueryResult = NonNullable<Awaited<ReturnType<typeof getEfficiency>>>
export type GetEfficiencyQueryError = ErrorResponse


export function useGetEfficiency<TData = Awaited<ReturnType<typeof getEfficiency>>, TError = ErrorResponse>(
 params: undefined |  GetEfficiencyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEfficiency>>,
          TError,
          Awaited<ReturnType<typeof getEfficiency>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEfficiency<TData = Awaited<ReturnType<typeof getEfficiency>>, TError = ErrorResponse>(
 params?: GetEfficiencyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEfficiency>>,
          TError,
          Awaited<ReturnType<typeof getEfficiency>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEfficiency<TData = Awaited<ReturnType<typeof getEfficiency>>, TError = ErrorResponse>(
 params?: GetEfficiencyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Embedded storage efficiency statistics
 */

export function useGetEfficiency<TData = Awaited<ReturnType<typeof getEfficiency>>, TError = ErrorResponse>(
 params?: GetEfficiencyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEfficiency>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEfficiencyQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Folds every member node's storage efficiency into one view, reporting the replicated footprint and the deduplicated one side by side: summing per-node bytes counts a part once per replica, which overstates how much data the cluster actually holds.
Served by a cluster-wide admin (odbadmin). A storage node sees only itself and answers with an error.

 * @summary Cluster-wide storage footprint
 */
export const getClusterStorage = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<ClusterStorage>(
      {url: `/api/v1/cluster/storage`, method: 'GET', signal
    },
      );
    }
  



export const getGetClusterStorageQueryKey = () => {
    return [
    `/api/v1/cluster/storage`
    ] as const;
    }

    
export const getGetClusterStorageQueryOptions = <TData = Awaited<ReturnType<typeof getClusterStorage>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClusterStorageQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClusterStorage>>> = ({ signal }) => getClusterStorage(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClusterStorageQueryResult = NonNullable<Awaited<ReturnType<typeof getClusterStorage>>>
export type GetClusterStorageQueryError = ErrorResponse


export function useGetClusterStorage<TData = Awaited<ReturnType<typeof getClusterStorage>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClusterStorage>>,
          TError,
          Awaited<ReturnType<typeof getClusterStorage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClusterStorage<TData = Awaited<ReturnType<typeof getClusterStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClusterStorage>>,
          TError,
          Awaited<ReturnType<typeof getClusterStorage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClusterStorage<TData = Awaited<ReturnType<typeof getClusterStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Cluster-wide storage footprint
 */

export function useGetClusterStorage<TData = Awaited<ReturnType<typeof getClusterStorage>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClusterStorage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClusterStorageQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Breaks a record signal's flushed parts down by stream, or by a stream label's values: rows, decoded bytes, an approximate compressed share, and per-column distinct estimates. This is the heaviest call the storage engine exposes — every accounted byte column of every live part is read and decoded once — so it is an on-demand drill-down, not something to poll. Narrow it with `columns` when only one column is in question.

 * @summary Attribute a signal's stored bytes to streams
 */
export const getStreamCosts = (
    params: GetStreamCostsParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<StreamCosts>(
      {url: `/api/v1/storage/stream-costs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetStreamCostsQueryKey = (params?: GetStreamCostsParams,) => {
    return [
    `/api/v1/storage/stream-costs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetStreamCostsQueryOptions = <TData = Awaited<ReturnType<typeof getStreamCosts>>, TError = ErrorResponse>(params: GetStreamCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStreamCostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStreamCosts>>> = ({ signal }) => getStreamCosts(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStreamCostsQueryResult = NonNullable<Awaited<ReturnType<typeof getStreamCosts>>>
export type GetStreamCostsQueryError = ErrorResponse


export function useGetStreamCosts<TData = Awaited<ReturnType<typeof getStreamCosts>>, TError = ErrorResponse>(
 params: GetStreamCostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStreamCosts>>,
          TError,
          Awaited<ReturnType<typeof getStreamCosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStreamCosts<TData = Awaited<ReturnType<typeof getStreamCosts>>, TError = ErrorResponse>(
 params: GetStreamCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStreamCosts>>,
          TError,
          Awaited<ReturnType<typeof getStreamCosts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStreamCosts<TData = Awaited<ReturnType<typeof getStreamCosts>>, TError = ErrorResponse>(
 params: GetStreamCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Attribute a signal's stored bytes to streams
 */

export function useGetStreamCosts<TData = Awaited<ReturnType<typeof getStreamCosts>>, TError = ErrorResponse>(
 params: GetStreamCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStreamCosts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStreamCostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Execute a maintenance action against the running process.
 * @summary Run a runtime control action
 */
export const runAction = (
    action: ActionName,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ActionResult>(
      {url: `/api/v1/actions/${action}`, method: 'POST', signal
    },
      );
    }
  


export const getRunActionMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runAction>>, TError,{action: ActionName}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof runAction>>, TError,{action: ActionName}, TContext> => {

const mutationKey = ['runAction'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runAction>>, {action: ActionName}> = (props) => {
          const {action} = props ?? {};

          return  runAction(action,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RunActionMutationResult = NonNullable<Awaited<ReturnType<typeof runAction>>>
    
    export type RunActionMutationError = ErrorResponse

    /**
 * @summary Run a runtime control action
 */
export const useRunAction = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runAction>>, TError,{action: ActionName}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runAction>>,
        TError,
        {action: ActionName},
        TContext
      > => {

      const mutationOptions = getRunActionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
