// Code generated by ogen, DO NOT EDIT.

package lokiapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DetectedLabels implements detectedLabels operation.
	//
	// Get detected labels.
	// Used by Grafana to test Logs Drilldown availability.
	//
	// GET /loki/api/v1/detected_labels
	DetectedLabels(ctx context.Context, params DetectedLabelsParams) (*DetectedLabels, error)
	// DrilldownLimits implements drilldownLimits operation.
	//
	// Get drilldown limits.
	// Used by Grafana to get limits from Loki.
	//
	// GET /loki/api/v1/drilldown-limits
	DrilldownLimits(ctx context.Context) (*DrilldownLimits, error)
	// IndexStats implements indexStats operation.
	//
	// Get index stats.
	//
	// GET /loki/api/v1/index/stats
	IndexStats(ctx context.Context, params IndexStatsParams) (*IndexStats, error)
	// LabelValues implements labelValues operation.
	//
	// Get values of label.
	//
	// GET /loki/api/v1/label/{name}/values
	LabelValues(ctx context.Context, params LabelValuesParams) (*Values, error)
	// Labels implements labels operation.
	//
	// Get labels.
	// Used by Grafana to test connection to Loki.
	//
	// GET /loki/api/v1/labels
	Labels(ctx context.Context, params LabelsParams) (*Labels, error)
	// Push implements push operation.
	//
	// Push data.
	//
	// POST /loki/api/v1/push
	Push(ctx context.Context, req PushReq) error
	// Query implements query operation.
	//
	// Query.
	//
	// GET /loki/api/v1/query
	Query(ctx context.Context, params QueryParams) (*QueryResponse, error)
	// QueryRange implements queryRange operation.
	//
	// Query range.
	//
	// GET /loki/api/v1/query_range
	QueryRange(ctx context.Context, params QueryRangeParams) (*QueryResponse, error)
	// QueryVolume implements queryVolume operation.
	//
	// Query the index for volume information about label and label-value combinations.
	//
	// GET /loki/api/v1/index/volume
	QueryVolume(ctx context.Context, params QueryVolumeParams) (*QueryResponse, error)
	// QueryVolumeRange implements queryVolumeRange operation.
	//
	// Query the index for volume information about label and label-value combinations.
	//
	// GET /loki/api/v1/index/volume_range
	QueryVolumeRange(ctx context.Context, params QueryVolumeRangeParams) (*QueryResponse, error)
	// Series implements series operation.
	//
	// Get series.
	//
	// GET /loki/api/v1/series
	Series(ctx context.Context, params SeriesParams) (*Maps, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
