/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Supported runtime control actions.
 */
export type ActionName = typeof ActionName[keyof typeof ActionName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionName = {
  gc: 'gc',
  'free-os-memory': 'free-os-memory',
  'storage-maintain': 'storage-maintain',
} as const;
