/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { ActionName } from './actionName';

export interface ActionResult {
  action: ActionName;
  ok: boolean;
  /** Human-readable outcome. */
  message: string;
  /** Heap bytes released, for memory-reclaiming actions. */
  freed_bytes?: number;
}
