/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Ingestion admission counters for a tenant.
 */
export interface AdmissionStats {
  accepted: number;
  /** Rejected as out-of-order. */
  rejected_ooo: number;
  /** Rejected by rate limit. */
  rejected_rate: number;
  /** Rejected by cardinality limit. */
  rejected_cardinality: number;
  /** Rejected due to in-flight admission pressure. */
  rejected_in_flight: number;
  sampled_dropped: number;
  overflowed: number;
}
