/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { ClusterNodeStatus } from './clusterNodeStatus';
import type { ClusterTenantStorage } from './clusterTenantStorage';

/**
 * The cluster's storage footprint, counted both ways: once per stored copy and once per distinct part.

 */
export interface ClusterStorage {
  /** The cluster's configured replication factor, as this aggregator is configured. */
  replication_factor: number;
  /** Whether every member answered, and answered with the part identities deduplication needs. False makes every logical figure below a LOWER BOUND: a node that did not answer contributes no parts to the union, so a part only it holds is missing from the count entirely. See `nodes` for which node failed.
 */
  complete: boolean;
  /** Every member the aggregator asked, answering or not. */
  nodes: ClusterNodeStatus[];
  tenants: ClusterTenantStorage[];
}
