/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Whether a member answered the aggregator.
 */
export type ClusterNodeState = typeof ClusterNodeState[keyof typeof ClusterNodeState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterNodeState = {
  ok: 'ok',
  unreachable: 'unreachable',
} as const;
