/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { Signal } from './signal';
import type { ClusterNodeSignalStorage } from './clusterNodeSignalStorage';

/**
 * One (tenant, signal)'s footprint across the cluster. The logical figures deduplicate by part id; the physical ones do not, and their ratio is the replication actually achieved — which is not the configured factor while a rebalance is in flight or a replica is missing.

 */
export interface ClusterSignalStorage {
  signal: Signal;
  /** Stored bytes of the distinct parts the cluster holds — a part mirrored to several owners is counted once, at the size the first node reporting it gave. This is the number to plan capacity against. It is a LOWER BOUND when `complete` is false: parts held only by a node that did not answer are missing from the union entirely.
 */
  logical_bytes: number;
  /** Sum of every answering node's stored bytes, counting a part once per replica. This is what the disks actually hold, and it is deliberately not `logical_bytes` times the replication factor: under-replication and in-flight rebalancing move the two apart, which is exactly when the difference is worth looking at.
 */
  physical_bytes: number;
  /** Distinct part ids across the answering nodes. */
  logical_parts: number;
  /** Sum of the answering nodes' part counts — one count per stored replica. */
  physical_parts: number;
  /** Samples or records in the distinct parts, deduplicated the same way as `logical_bytes` and an underestimate under the same condition.
 */
  logical_points: number;
  /** Sum of the answering nodes' point counts, counting a replicated part once per replica. */
  physical_points: number;
  /** The cluster's configured replication factor, repeated here so the two byte figures read on their own. */
  replication_factor: number;
  /** What each node contributed, ordered by node id. Only nodes holding data for this (tenant, signal) appear: a node that holds none of it and a node that did not answer are both absent here, and the report's `nodes` is what tells them apart.
 */
  nodes: ClusterNodeSignalStorage[];
}
