/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { ClusterNodeState } from './clusterNodeState';

/**
 * One member node's participation in this report.
 */
export interface ClusterNodeStatus {
  /** Member id in the ring. */
  node: string;
  /** Admin API base URL the aggregator used. */
  addr?: string;
  status: ClusterNodeState;
  /** Why the node did not answer. Present only when status is unreachable. */
  error?: string;
  /** How long the node took to answer. */
  duration_seconds?: number;
}
