/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { HealthStatus } from './healthStatus';

export interface ComponentHealth {
  /** Component/service name. */
  name: string;
  status: HealthStatus;
  /** Listen address, when the component is an HTTP server. */
  addr?: string;
  /** Last error, when unhealthy. */
  error?: string;
}
