/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Decoded-column cache, summed across metric engines.
 */
export interface DecodeCacheStats {
  hits: number;
  misses: number;
  bytes: number;
  /** Cached blocks. */
  items: number;
}
