/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { NodeParamParameter } from './nodeParamParameter';
import type { RecordSignal } from './recordSignal';

export type GetStreamCostsParams = {
/**
 * Addresses one member node by its ring id instead of the whole cluster. A cluster-wide admin forwards the request to that member and returns its answer verbatim; unset, it aggregates every member as usual. Names come from /api/v1/cluster/nodes.
This is what makes the per-node-only operations reachable from the cluster panel: stream cost attribution and the maintenance actions are refused cluster-wide, but are ordinary requests once addressed to a node. A storage node ignores the parameter -- it is the only node it can answer for.

 */
node?: NodeParamParameter;
/**
 * Signal to attribute. Metrics carry no per-record columns, so they are not attributable.
 */
signal: RecordSignal;
/**
 * Tenant to inspect. Empty selects the instance's default tenant.
 */
tenant?: string;
/**
 * Stream label (a resource or scope attribute name, e.g. "service.name") whose value keys the report. Empty groups by raw stream id.

 */
group_by?: string;
/**
 * Restricts the byte columns decoded and attributed. Empty accounts every byte column.
 */
columns?: string[];
/**
 * Keeps only the N costliest groups by raw bytes. 0 returns every group.
 */
top_n?: number;
};
