/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * What is answering: one storage node, or a cluster aggregator standing in front of several. The two serve the same API but not the same operations -- stream cost attribution and the maintenance actions are per-node only, because attribution would decode each replicated part once per replica and an action that half-succeeds across a cluster has no partial-failure contract here. A client that cannot tell them apart can only offer those controls and let them fail.
Optional rather than required so a newer aggregator can still read an older node's info during a rolling upgrade; absent means the same thing as "node".

 */
export type InstanceMode = typeof InstanceMode[keyof typeof InstanceMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InstanceMode = {
  node: 'node',
  cluster: 'cluster',
} as const;
