/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Background maintenance loop liveness and recency. A growing cycle duration means compaction is falling behind the ingest rate.

 */
export interface MaintenanceStats {
  /** Completed maintenance cycles since process start (the loop-liveness probe). */
  cycles: number;
  /** Start of the most recent cycle, once one has run. */
  last_cycle_start?: string;
  /** Duration of the most recent completed cycle. */
  last_cycle_duration_seconds: number;
  /** Engine tasks (flush/merge or replica refresh) dispatched in the most recent cycle. */
  last_cycle_tasks: number;
}
