/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * One flushed part's identity and size.
 */
export interface PartEfficiency {
  /** The part's backend key prefix. It is assigned once by the node that wrote the part and is preserved verbatim when the part is mirrored, so the same id on two nodes is the same data — which is what makes cluster-wide deduplication possible.
 */
  id: string;
  /** Sum of the part's backend object sizes on this node. */
  bytes: number;
  /** Samples (metrics) or records (logs/traces/profiles) in the part. */
  rows: number;
  /** Distinct series/streams in the part. */
  series: number;
}
