/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { PartColumn } from './partColumn';
import type { PartEfficiencyOtherBytes } from './partEfficiencyOtherBytes';

/**
 * One flushed part's identity and size.
 */
export interface PartEfficiency {
  /** The part's backend key prefix. It is assigned once by the node that wrote the part and is preserved verbatim when the part is mirrored, so the same id on two nodes is the same data — which is what makes cluster-wide deduplication possible.
 */
  id: string;
  /** Sum of the part's backend object sizes on this node. */
  bytes: number;
  /** Samples (metrics) or records (logs/traces/profiles) in the part. */
  rows: number;
  /** Distinct series/streams in the part. */
  series: number;
  /** The part's columns, each with its physical layout and the size of its object. Present only when the part was read in enough detail to know them; a column whose values all collapsed to a constant has no object and so reports 0 bytes. Together with `other_bytes` the column sizes sum to `bytes`, which is what makes a single column's share of a store — the metric timestamp column's, say — measurable from the API.
 */
  columns?: PartColumn[];
  /** Every non-column object in the part, keyed by its name under the part prefix (`manifest`, `marks`, and the engine's own indexes, e.g. `identity`, `sidx`, `stats`, `blooms`). With the `columns` sizes it sums to `bytes`.
 */
  other_bytes?: PartEfficiencyOtherBytes;
}
