/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Signal stored as records, and so attributable per stream. Metrics are excluded: their samples carry no per-record columns to attribute (use label cardinality there instead).

 */
export type RecordSignal = typeof RecordSignal[keyof typeof RecordSignal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecordSignal = {
  traces: 'traces',
  logs: 'logs',
  profiles: 'profiles',
} as const;
