/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { Signal } from './signal';

/**
 * One (tenant, signal)'s flushed-data shape: how many points it stores, in how many bytes, and how well they compress. Stored bytes are this node's on-disk footprint — under erasure coding with slot filtering that is the local shard, not the cluster-wide total.

 */
export interface SignalEfficiency {
  signal: Signal;
  /** Distinct series/streams (head and flushed). */
  series: number;
  /** Flushed part count. */
  parts: number;
  /** Total samples (metrics) or records (logs/traces/profiles). */
  points: number;
  /** Sum of the parts' backend object sizes on this node. */
  stored_bytes: number;
  /** Stored bytes per point — the per-sample storage cost. */
  bytes_per_point: number;
  /** Uncompressed logical size of the stored points; present only for metrics (points x 16), the record signals' per-record logical size is not recorded.
 */
  logical_bytes?: number;
  /** Logical/stored ratio (e.g. 8.0 = stored at 1/8th of logical); present only when logical size is known. */
  compression_ratio?: number;
}
