/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { ColumnCost } from './columnCost';

/**
 * One group's share of a signal's storage.
 */
export interface StreamCost {
  /** The group_by label's value, or the stream id. Empty means the label is absent. */
  key: string;
  /** Distinct streams folded into this group. */
  streams: number;
  rows: number;
  /** Decoded footprint of the group's rows over the accounted columns. */
  raw_bytes: number;
  /** Approximate compressed share. Compression is per column per frame and a frame spans whatever streams its rows fall in, so each frame's size is apportioned across the groups holding its rows by their raw-byte share.
 */
  disk_bytes: number;
  /** Whether per-column distinct counts were measured for this group. False means they are 0 because the group fell outside the sketch budget, not because the values are unique.
 */
  distinct_estimated: boolean;
  columns: ColumnCost[];
}
