/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { RecordSignal } from './recordSignal';
import type { StreamCost } from './streamCost';

/**
 * Per-stream (or per-label-value) storage cost attribution for one signal.
 */
export interface StreamCosts {
  /** False when no embedded engine is active, in which case groups is empty. */
  storage_enabled: boolean;
  signal: RecordSignal;
  tenant: string;
  /** Label whose values key the report. Empty means the report is keyed by stream id. */
  group_by?: string;
  /** Costliest groups first. Empty when the tenant has no engine for the signal. */
  groups: StreamCost[];
}
