/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */

export interface TableStats {
  database: string;
  table: string;
  rows: number;
  /** Compressed on-disk size. */
  bytes_on_disk: number;
  data_uncompressed_bytes: number;
  /** Number of active parts. */
  parts: number;
  /** Earliest partition time, when available. */
  min_time?: string;
  /** Latest partition time, when available. */
  max_time?: string;
}
