/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * oteldb admin panel API
 * Administrative API for an oteldb instance: instance info and effective configuration, per-signal component health, ClickHouse storage statistics, and runtime controls.

 * OpenAPI spec version: 0.1.0
 */
import type { SignalEfficiency } from './signalEfficiency';

/**
 * One tenant's per-signal efficiency breakdown.
 */
export interface TenantEfficiency {
  /** Tenant identifier. */
  tenant: string;
  signals: SignalEfficiency[];
}
