// Code generated by ogen, DO NOT EDIT.

package multitenancyapi

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrRespStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AuthorizeRequest
type AuthorizeRequest struct {
	Credential string                      `json:"credential"`
	Operation  AuthorizeRequestOperation   `json:"operation"`
	Metadata   OptAuthorizeRequestMetadata `json:"metadata"`
}

// GetCredential returns the value of Credential.
func (s *AuthorizeRequest) GetCredential() string {
	return s.Credential
}

// GetOperation returns the value of Operation.
func (s *AuthorizeRequest) GetOperation() AuthorizeRequestOperation {
	return s.Operation
}

// GetMetadata returns the value of Metadata.
func (s *AuthorizeRequest) GetMetadata() OptAuthorizeRequestMetadata {
	return s.Metadata
}

// SetCredential sets the value of Credential.
func (s *AuthorizeRequest) SetCredential(val string) {
	s.Credential = val
}

// SetOperation sets the value of Operation.
func (s *AuthorizeRequest) SetOperation(val AuthorizeRequestOperation) {
	s.Operation = val
}

// SetMetadata sets the value of Metadata.
func (s *AuthorizeRequest) SetMetadata(val OptAuthorizeRequestMetadata) {
	s.Metadata = val
}

type AuthorizeRequestMetadata map[string]string

func (s *AuthorizeRequestMetadata) init() AuthorizeRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

type AuthorizeRequestOperation string

const (
	AuthorizeRequestOperationRead  AuthorizeRequestOperation = "read"
	AuthorizeRequestOperationWrite AuthorizeRequestOperation = "write"
)

// AllValues returns all AuthorizeRequestOperation values.
func (AuthorizeRequestOperation) AllValues() []AuthorizeRequestOperation {
	return []AuthorizeRequestOperation{
		AuthorizeRequestOperationRead,
		AuthorizeRequestOperationWrite,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AuthorizeRequestOperation) MarshalText() ([]byte, error) {
	switch s {
	case AuthorizeRequestOperationRead:
		return []byte(s), nil
	case AuthorizeRequestOperationWrite:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AuthorizeRequestOperation) UnmarshalText(data []byte) error {
	switch AuthorizeRequestOperation(data) {
	case AuthorizeRequestOperationRead:
		*s = AuthorizeRequestOperationRead
		return nil
	case AuthorizeRequestOperationWrite:
		*s = AuthorizeRequestOperationWrite
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/AuthorizeResponse
type AuthorizeResponse struct {
	TenantIds         []string           `json:"tenant_ids"`
	Username          OptString          `json:"username"`
	QuotaKey          OptString          `json:"quota_key"`
	ResourceSelectors []ResourceSelector `json:"resource_selectors"`
	Restrictions      OptRestrictions    `json:"restrictions"`
	// Cache TTL in seconds.
	CacheTTL OptInt `json:"cache_ttl"`
}

// GetTenantIds returns the value of TenantIds.
func (s *AuthorizeResponse) GetTenantIds() []string {
	return s.TenantIds
}

// GetUsername returns the value of Username.
func (s *AuthorizeResponse) GetUsername() OptString {
	return s.Username
}

// GetQuotaKey returns the value of QuotaKey.
func (s *AuthorizeResponse) GetQuotaKey() OptString {
	return s.QuotaKey
}

// GetResourceSelectors returns the value of ResourceSelectors.
func (s *AuthorizeResponse) GetResourceSelectors() []ResourceSelector {
	return s.ResourceSelectors
}

// GetRestrictions returns the value of Restrictions.
func (s *AuthorizeResponse) GetRestrictions() OptRestrictions {
	return s.Restrictions
}

// GetCacheTTL returns the value of CacheTTL.
func (s *AuthorizeResponse) GetCacheTTL() OptInt {
	return s.CacheTTL
}

// SetTenantIds sets the value of TenantIds.
func (s *AuthorizeResponse) SetTenantIds(val []string) {
	s.TenantIds = val
}

// SetUsername sets the value of Username.
func (s *AuthorizeResponse) SetUsername(val OptString) {
	s.Username = val
}

// SetQuotaKey sets the value of QuotaKey.
func (s *AuthorizeResponse) SetQuotaKey(val OptString) {
	s.QuotaKey = val
}

// SetResourceSelectors sets the value of ResourceSelectors.
func (s *AuthorizeResponse) SetResourceSelectors(val []ResourceSelector) {
	s.ResourceSelectors = val
}

// SetRestrictions sets the value of Restrictions.
func (s *AuthorizeResponse) SetRestrictions(val OptRestrictions) {
	s.Restrictions = val
}

// SetCacheTTL sets the value of CacheTTL.
func (s *AuthorizeResponse) SetCacheTTL(val OptInt) {
	s.CacheTTL = val
}

func (*AuthorizeResponse) authorizeRes() {}

// AuthorizeUnauthorized is response for Authorize operation.
type AuthorizeUnauthorized struct{}

func (*AuthorizeUnauthorized) authorizeRes() {}

type ErrResp struct {
	Error OptString `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrResp) GetError() OptString {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrResp) SetError(val OptString) {
	s.Error = val
}

// ErrRespStatusCode wraps ErrResp with StatusCode.
type ErrRespStatusCode struct {
	StatusCode int
	Response   ErrResp
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrRespStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrRespStatusCode) GetResponse() ErrResp {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrRespStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrRespStatusCode) SetResponse(val ErrResp) {
	s.Response = val
}

// NewOptAuthorizeRequestMetadata returns new OptAuthorizeRequestMetadata with value set to v.
func NewOptAuthorizeRequestMetadata(v AuthorizeRequestMetadata) OptAuthorizeRequestMetadata {
	return OptAuthorizeRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptAuthorizeRequestMetadata is optional AuthorizeRequestMetadata.
type OptAuthorizeRequestMetadata struct {
	Value AuthorizeRequestMetadata
	Set   bool
}

// IsSet returns true if OptAuthorizeRequestMetadata was set.
func (o OptAuthorizeRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAuthorizeRequestMetadata) Reset() {
	var v AuthorizeRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAuthorizeRequestMetadata) SetTo(v AuthorizeRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAuthorizeRequestMetadata) Get() (v AuthorizeRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAuthorizeRequestMetadata) Or(d AuthorizeRequestMetadata) AuthorizeRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRestrictions returns new OptRestrictions with value set to v.
func NewOptRestrictions(v Restrictions) OptRestrictions {
	return OptRestrictions{
		Value: v,
		Set:   true,
	}
}

// OptRestrictions is optional Restrictions.
type OptRestrictions struct {
	Value Restrictions
	Set   bool
}

// IsSet returns true if OptRestrictions was set.
func (o OptRestrictions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRestrictions) Reset() {
	var v Restrictions
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRestrictions) SetTo(v Restrictions) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRestrictions) Get() (v Restrictions, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRestrictions) Or(d Restrictions) Restrictions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint64 returns new OptUint64 with value set to v.
func NewOptUint64(v uint64) OptUint64 {
	return OptUint64{
		Value: v,
		Set:   true,
	}
}

// OptUint64 is optional uint64.
type OptUint64 struct {
	Value uint64
	Set   bool
}

// IsSet returns true if OptUint64 was set.
func (o OptUint64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint64) Reset() {
	var v uint64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint64) SetTo(v uint64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint64) Get() (v uint64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint64) Or(d uint64) uint64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ResourceSelector
type ResourceSelector struct {
	Key   string             `json:"key"`
	Op    ResourceSelectorOp `json:"op"`
	Value string             `json:"value"`
}

// GetKey returns the value of Key.
func (s *ResourceSelector) GetKey() string {
	return s.Key
}

// GetOp returns the value of Op.
func (s *ResourceSelector) GetOp() ResourceSelectorOp {
	return s.Op
}

// GetValue returns the value of Value.
func (s *ResourceSelector) GetValue() string {
	return s.Value
}

// SetKey sets the value of Key.
func (s *ResourceSelector) SetKey(val string) {
	s.Key = val
}

// SetOp sets the value of Op.
func (s *ResourceSelector) SetOp(val ResourceSelectorOp) {
	s.Op = val
}

// SetValue sets the value of Value.
func (s *ResourceSelector) SetValue(val string) {
	s.Value = val
}

type ResourceSelectorOp string

const (
	ResourceSelectorOpEq  ResourceSelectorOp = "eq"
	ResourceSelectorOpNeq ResourceSelectorOp = "neq"
	ResourceSelectorOpRe  ResourceSelectorOp = "re"
	ResourceSelectorOpNre ResourceSelectorOp = "nre"
)

// AllValues returns all ResourceSelectorOp values.
func (ResourceSelectorOp) AllValues() []ResourceSelectorOp {
	return []ResourceSelectorOp{
		ResourceSelectorOpEq,
		ResourceSelectorOpNeq,
		ResourceSelectorOpRe,
		ResourceSelectorOpNre,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceSelectorOp) MarshalText() ([]byte, error) {
	switch s {
	case ResourceSelectorOpEq:
		return []byte(s), nil
	case ResourceSelectorOpNeq:
		return []byte(s), nil
	case ResourceSelectorOpRe:
		return []byte(s), nil
	case ResourceSelectorOpNre:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceSelectorOp) UnmarshalText(data []byte) error {
	switch ResourceSelectorOp(data) {
	case ResourceSelectorOpEq:
		*s = ResourceSelectorOpEq
		return nil
	case ResourceSelectorOpNeq:
		*s = ResourceSelectorOpNeq
		return nil
	case ResourceSelectorOpRe:
		*s = ResourceSelectorOpRe
		return nil
	case ResourceSelectorOpNre:
		*s = ResourceSelectorOpNre
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Restrictions
type Restrictions struct {
	MaxMemoryUsageBytes OptUint64 `json:"max_memory_usage_bytes"`
	MaxExecutionTimeMs  OptInt    `json:"max_execution_time_ms"`
	MaxResultRows       OptUint64 `json:"max_result_rows"`
}

// GetMaxMemoryUsageBytes returns the value of MaxMemoryUsageBytes.
func (s *Restrictions) GetMaxMemoryUsageBytes() OptUint64 {
	return s.MaxMemoryUsageBytes
}

// GetMaxExecutionTimeMs returns the value of MaxExecutionTimeMs.
func (s *Restrictions) GetMaxExecutionTimeMs() OptInt {
	return s.MaxExecutionTimeMs
}

// GetMaxResultRows returns the value of MaxResultRows.
func (s *Restrictions) GetMaxResultRows() OptUint64 {
	return s.MaxResultRows
}

// SetMaxMemoryUsageBytes sets the value of MaxMemoryUsageBytes.
func (s *Restrictions) SetMaxMemoryUsageBytes(val OptUint64) {
	s.MaxMemoryUsageBytes = val
}

// SetMaxExecutionTimeMs sets the value of MaxExecutionTimeMs.
func (s *Restrictions) SetMaxExecutionTimeMs(val OptInt) {
	s.MaxExecutionTimeMs = val
}

// SetMaxResultRows sets the value of MaxResultRows.
func (s *Restrictions) SetMaxResultRows(val OptUint64) {
	s.MaxResultRows = val
}
